import { TestContent, QuestionType } from '../types';

export const GrammarTest1: TestContent = {
    meta: {
        id: 'test-grammar-01',
        title: 'Test 1: Nouns, Articles & Pronouns',
        description: 'Bài kiểm tra tổng hợp về Danh từ, Mạo từ và Đại từ. Hãy cố gắng đạt điểm cao nhất nhé!',
        level: 'Beginner',
        estimatedTime: 20,
        totalQuestions: 30,
        passScore: 80,
    },
    questions: [
        // --- NOUNS (Questions 1-10) ---
        {
            id: 'g1-q1',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Chọn danh từ đếm được (Countable Noun):",
            options: ["Water", "Rice", "Book", "Love"],
            correctAnswer: "Book",
            explanation: "Quy tắc: Danh từ đếm được là những thứ ta có thể đếm 1, 2, 3... trực tiếp. Chúng mình có thể nói 'one book', 'two books'. Nước (Water), gạo (Rice) và tình yêu (Love) là danh từ không đếm được.",
        },
        {
            id: 'g1-q2',
            type: QuestionType.FILL_GAP,
            question: "Chuyển từ 'knife' sang số nhiều: _____",
            correctAnswer: "knives",
            explanation: "Quy tắc: Danh từ kết thúc bằng 'f' hoặc 'fe', ta đổi thành 'ves'. Ví dụ: knife -> knives, leaf -> leaves.",
        },
        {
            id: 'g1-q3',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Chọn dạng số nhiều đúng của 'child':",
            options: ["childs", "childrens", "children", "childes"],
            correctAnswer: "children",
            explanation: "Quy tắc: Đây là danh từ bất quy tắc. 1 đứa trẻ là 'child', từ 2 đứa trở lên phải dùng 'children'. Đừng thêm 's' vào nhé!",
        },
        {
            id: 'g1-q4',
            type: QuestionType.FILL_GAP,
            question: "Số nhiều của 'person' là _____",
            correctAnswer: "people",
            explanation: "Quy tắc: Một người là 'person', nhiều người là 'people'. Đây là trường hợp bất quy tắc cực kỳ phổ biến.",
        },
        {
            id: 'g1-q5',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Từ nào sau đây LUÔN viết hoa (Proper Noun)?",
            options: ["country", "monday", "city", "street"],
            correctAnswer: "monday",
            explanation: "Quy tắc: Các thứ trong tuần (Monday, Tuesday...), tháng (January...), tên riêng và địa danh luôn phải viết hoa chữ cái đầu.",
        },
        {
            id: 'g1-q6',
            type: QuestionType.FILL_GAP,
            question: "Dạng số nhiều của 'city' là _____",
            correctAnswer: "cities",
            explanation: "Quy tắc: Danh từ kết thúc bằng 'phụ âm + y', ta đổi 'y' thành 'i' và thêm 'es'. Ví dụ: city -> cities, baby -> babies.",
        },
        {
            id: 'g1-q7',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Số nhiều của 'tooth' là:",
            options: ["tooths", "teeths", "teeth", "toothes"],
            correctAnswer: "teeth",
            explanation: "Quy tắc: Danh từ bất quy tắc đổi 'oo' thành 'ee'. Tương tự: foot -> feet.",
        },
        {
            id: 'g1-q8',
            type: QuestionType.FILL_GAP,
            question: "Dạng số nhiều của 'tomato' là _____",
            correctAnswer: "tomatoes",
            explanation: "Quy tắc: Danh từ kết thúc bằng 'o', thông thường ta thêm 'es'. Ví dụ: tomato -> tomatoes, potato -> potatoes.",
        },
        {
            id: 'g1-q9',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Chọn danh từ KHÔNG đếm được (Uncountable Noun):",
            options: ["Apple", "Money", "Chair", "Student"],
            correctAnswer: "Money",
            explanation: "Lưu ý: Trong tiếng Anh, 'Money' (tiền) được coi là danh từ không đếm được. Chúng mình đếm 'dollars' hay 'dong' chứ không đếm 'one money, two money'.",
        },
        {
            id: 'g1-q10',
            type: QuestionType.FILL_GAP,
            question: "Dạng số nhiều của 'sheep' là _____",
            correctAnswer: "sheep",
            explanation: "Quy tắc: Một số danh từ giữ nguyên hình thức ở cả số ít và số nhiều. Ví dụ: sheep, fish, deer.",
        },

        // --- ARTICLES (Questions 11-20) ---
        {
            id: 'g1-q11',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "I have _____ idea for our weekend trip.",
            options: ["a", "an", "the", "zero"],
            correctAnswer: "an",
            explanation: "Quy tắc: Sử dụng 'an' trước danh từ bắt đầu bằng nguyên âm (u, e, o, a, i). 'Idea' bắt đầu bằng 'i'.",
        },
        {
            id: 'g1-q12',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "She is staying at _____ hotel in the city center.",
            options: ["a", "an", "the", "zero"],
            correctAnswer: "a",
            explanation: "Quy tắc: Dùng 'a' khi nhắc đến một vật lần đầu tiên hoặc chưa xác định cụ thể. 'Hotel' bắt đầu bằng phụ âm 'h'.",
        },
        {
            id: 'g1-q13',
            type: QuestionType.FILL_GAP,
            question: "He can play _____ guitar very well.",
            correctAnswer: "the",
            explanation: "Quy tắc: Luôn dùng mạo từ 'the' trước tên các loại nhạc cụ (the guitar, the piano, the violin...).",
        },
        {
            id: 'g1-q14',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "_____ moon looks beautiful tonight.",
            options: ["A", "An", "The", "Zero"],
            correctAnswer: "The",
            explanation: "Quy tắc: Dùng 'the' cho những vật duy nhất trên đời như: the Sun, the Moon, the Earth.",
        },
        {
            id: 'g1-q15',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "We usually have _____ breakfast at 7 AM.",
            options: ["a", "an", "the", "zero (không điền)"],
            correctAnswer: "zero (không điền)",
            explanation: "Quy tắc: Thông thường, chúng mình KHÔNG dùng mạo từ trước tên các bữa ăn (breakfast, lunch, dinner).",
        },
        {
            id: 'g1-q16',
            type: QuestionType.FILL_GAP,
            question: "It takes me _____ hour to get home.",
            correctAnswer: "an",
            explanation: "Cẩn thận nè: 'hour' bắt đầu bằng âm câm 'h', nên cách phát âm thực tế bắt đầu bằng nguyên âm 'o'. Do đó ta phải dùng 'an'.",
        },
        {
            id: 'g1-q17',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "_____ Hanoi is the capital of Vietnam.",
            options: ["A", "An", "The", "Zero (không điền)"],
            correctAnswer: "Zero (không điền)",
            explanation: "Quy tắc: Không dùng mạo từ trước tên hầu hết các quốc gia và thành phố (Vietnam, Hanoi, Japan...).",
        },
        {
            id: 'g1-q18',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "This is _____ best book I have ever read.",
            options: ["a", "an", "the", "zero"],
            correctAnswer: "the",
            explanation: "Quy tắc: Luôn sử dụng 'the' trước tính từ so sánh nhất (the best, the most beautiful, the tallest...).",
        },
        {
            id: 'g1-q19',
            type: QuestionType.FILL_GAP,
            question: "I saw a cat. _____ cat was black.",
            correctAnswer: "The",
            explanation: "Quy tắc: Khi một vật được nhắc lại lần thứ hai (đã xác định), ta dùng 'the'. Lần đầu dùng 'a cat', lần sau dùng 'the cat'.",
        },
        {
            id: 'g1-q20',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "He is _____ university student.",
            options: ["a", "an", "the", "zero"],
            correctAnswer: "a",
            explanation: "Cẩn thận nè: Mặc dù bắt đầu bằng chữ 'u' nhưng 'university' phát âm là /ju:/ (bắt đầu bằng âm /j/ là phụ âm), nên ta dùng 'a'.",
        },

        // --- PRONOUNS (Questions 21-30) ---
        {
            id: 'g1-q21',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "_____ are going to the cinema tonight.",
            options: ["We", "Us", "Our", "Ours"],
            correctAnswer: "We",
            explanation: "Vợ ơi, đầu câu làm chủ ngữ thì mình phải dùng đại từ nhân xưng chủ ngữ (I, You, We, They, He, She, It).",
        },
        {
            id: 'g1-q22',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Can you help _____ with this exercise?",
            options: ["I", "me", "my", "mine"],
            correctAnswer: "me",
            explanation: "Sau động từ (help) đóng vai trò tân ngữ, mình phải dùng đại từ tân ngữ (me, you, us, them, him, her, it).",
        },
        {
            id: 'g1-q23',
            type: QuestionType.FILL_GAP,
            question: "This is my brother. _____ name is Nam.",
            correctAnswer: "His",
            explanation: "Quy tắc: Tính từ sở hữu của 'He' (anh ấy) là 'His' (của anh ấy). Phải có danh từ đi kèm phía sau (His name).",
        },
        {
            id: 'g1-q24',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "They bought that house. It is _____.",
            options: ["them", "their", "theirs", "themselves"],
            correctAnswer: "theirs",
            explanation: "Quy tắc: Khi không có danh từ đi kèm phía sau, ta dùng đại từ sở hữu (theirs) thay vì tính từ sở hữu (their).",
        },
        {
            id: 'g1-q25',
            type: QuestionType.FILL_GAP,
            question: "I cooked this dinner by _____.",
            correctAnswer: "myself",
            explanation: "Quy tắc: Đại từ phản thân (myself, yourself...) dùng khi chủ ngữ và tân ngữ là cùng một người, hoặc để nhấn mạnh tự mình làm việc gì đó.",
        },
        {
            id: 'g1-q26',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Tòng loves _____ wife very much.",
            options: ["he", "him", "his", "himself"],
            correctAnswer: "his",
            explanation: "Quy tắc: 'Của anh ấy' + danh từ (wife) -> dùng tính từ sở hữu 'his'.",
        },
        {
            id: 'g1-q27',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Where are my keys? I can't find _____.",
            options: ["it", "they", "them", "their"],
            correctAnswer: "them",
            explanation: "Quy tắc: 'Keys' là số nhiều, nên khi làm tân ngữ thay thế ta dùng 'them'.",
        },
        {
            id: 'g1-q28',
            type: QuestionType.FILL_GAP,
            question: "She is looking at _____ in the mirror. (đổi từ she nhé)",
            correctAnswer: "herself",
            explanation: "Quy tắc: Cô ấy tự nhìn chính mình -> dùng đại từ phản thân 'herself'.",
        },
        {
            id: 'g1-q29',
            type: QuestionType.MULTIPLE_CHOICE,
            question: "Is this _____ pen?",
            options: ["you", "your", "yours", "yourself"],
            correctAnswer: "your",
            explanation: "Quy tắc: Trước danh từ (pen) cần một tính từ sở hữu để chỉ sự sở hữu (your pen).",
        },
        {
            id: 'g1-q30',
            type: QuestionType.REWRITE,
            question: "Rewrite: This bag belongs to me. (Dùng đại từ sở hữu mine)",
            correctAnswer: "This bag is mine",
            explanation: "Quy tắc: 'belongs to me' (thuộc về tôi) tương đương với 'is mine' (là của tôi).",
        }
    ]
};
